config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root 'posts#index'
  end
  root "static_pages#home"

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/user", to: "users#show"
  get '/users', to: 'users#index'
  post '/friends/create/:id', to: 'friendships#create'
  resources :friendships, only: %i[update destroy index]
  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true, length: { maximum: 150 }
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender, class_name: :User
  belongs_to :reciever, class_name: :User

  validates :sender_id, presence: true
  validates :reciever_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friendships, foreign_key: :sender_id
  has_many :inverse_friendships, class_name: :Friendship, foreign_key: :reciever_id

  def reject_request(sender)
    friendship = inverse_friendships.find { |f| f.sender == sender }
    friendship.destroy
  end

  def friend_with?(user)
    if inverse_friendships.find_by(sender_id: user.id,
                                   status: true) ||
       friendships.find_by(reciever_id: user.id, status: true)
      true
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split(' ')[0]
      user.last_name = auth.info.name.split(' ')[1]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include FriendshipsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_comment, only: [:destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.create(comment_params)

    if @comment.save
      flash[:success] = 'Comment added'

    else
      flash[:danger] = 'Successfully failed!'
    end
    redirect_to request.referrer
  end

  def destroy
    @comment.destroy
    redirect_to request.referrer
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:comment_text, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def new
    @friendship = Friendship.new
  end

  def create
    user = User.find(params[:id])
    friendship = current_user.friendships.create(reciever_id: user.id, status: false)
    if friendship.save
      flash[:success] = 'Friend request sent'
    else
      flash[:danger] = 'Failed'
    end
    redirect_to request.referrer
  end

  def destroy
    sender = params[:sender.id]
    reject_request(sender)
  end

  def index
    @friendships = current_user.friendships
    @inverse_friendships = current_user.inverse_friendships
  end

  def update
    sender = User.find(params[:id])
    friendship = current_user.inverse_friendships.find_by(sender_id: sender.id)
    friendship.update(status: 'true')
    friendship.save
    redirect_to request.referrer
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_find
  before_action :like_find, only: [:destroy]

  def create
    @post.likes.create(user_id: current_user.id)
    redirect_to request.referrer
  end

  def destroy
    @like.destroy
    redirect_to request.referrer
  end

  private

  def post_find
    @post = Post.find(params[:post_id])
  end

  def like_find
    @like = @post.likes.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[show index create edit update]

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post created successfully!'
      redirect_to root_path
    else
      flash.now[:danger] = "Content can't be empty!"
      @posts = Post.all
      render 'index'
    end
  end

  def edit; end

  def update; end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments.all
  end

  def index
    @post = current_user.posts.build if current_user
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show index]

  def show
    @user = current_user
    @posts = current_user.posts.all
  end

  def index
    @users = User.all
    @friendships = current_user.friendships
    @inverse_friendships = current_user.inverse_friendships
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend_list
    @friend_list = current_user.friendships.map { |friendship| friendship.reciever if friendship.status }
    @friend_list += current_user.inverse_friendships.map { |friendship| friendship.sender if friendship.status }
    @friend_list << current_user
    @friend_list.compact
  end

  def friend?(user)
    friend_list.include?(user)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def liked?(post)
    post.likes.find { |like| like.user_id == current_user.id }
  end

  def comment_author(comment)
    comment.user == current_user
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end

  def pending?(user)
    current_user.friendships.find_by(reciever_id: user.id, status: false)
  end

  def recieved?(user)
    current_user.inverse_friendships.find_by(sender_id: user.id, status: false)
  end
end

app/views/comments/_new.html.erb
<%= form_for([post[:post], Comment.new]) do |f| %>
  <div class="field-post com-field">
  <%= f.label :comment_text, 'Comment' %>
  <%= f.text_area :comment_text, placeholder: 'New comment', class: 'com-index field' %>
  <%= f.hidden_field :post_id, value: post[:post].id %>
  </div>
  <%= f.submit 'Comment', class: 'comment-btn index-com btn btn-primary' %>
<% end %>

app/views/friendships/index.html.erb
<div class="notifications-wrap">
  <div>
    <h4 class="notifications"><%=pluralize(@inverse_friendships.count, 'notification')%></h4>
    <div class="friend-requests">
      <% @inverse_friendships.reverse.each do |request|%>
        <div class="request">
          <p class="name"><%= gravatar_for request.sender %> <%= request.sender.first_name %> <%= request.sender.last_name %></p>
          <% if friend?(request.sender) %>
            <p>Friend request accepted</p>
          <% else %>
            <%= link_to 'Accept request', friendship_path(request.sender), method: :put, class: 'btn btn-primary' %>
          <% end %>
        </div>
      <% end %>
    </div>  
  </div>

  <div>
    <h4>Sent friend requests</h4>
    <div class="sent-requests">
      <% @friendships.reverse.each do |pending|%>
        <p class="sent-name"><%= gravatar_for pending.sender %> <%= pending.reciever.first_name %> <%= pending.reciever.last_name %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="timeline-center">
  <div class="timeline-row">
    <aside class="">
      <section class="post-form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
    <div class="">
      <ul class="post-list">
        <% @posts.reverse.each do |post| %>
          <li class="post-item post-index">
            <h1 class="post-img"><%= gravatar_for(post.user, options = { size: 50 }) %></h1>
            <h5><%= post.user.first_name %> <%= post.user.last_name %></h5>
            <div><%= post.content %></div>

            <% if liked?(post) %>
              <%= link_to post_like_path(post, liked?(post)), method: :delete , title: "Like" do%> 
              <i class="fa fa-thumbs-down disliked"></i> 
              <%end%>
            <% else %>
              <%= link_to post_likes_path(post), method: :post, title: "Dislike"  do%>
              <i class="fa fa-thumbs-up liked"></i> 
              <%end%>
            <% end %>

            <p><%= pluralize(post.likes.count, 'like') %></p>
            <p><%= pluralize(post.comments.count, 'comment') %></p>
            <p><%= link_to 'Post page', post_path(post.id) %></p>
          </li>
          <div class="comment-form">
            <%= render  'comments/new', post: {post: post} %>
          </div>
          <% post.comments.each do |comment| %>
            <div class="post-comments index-comment">
              <h1 class="post-img"><%= gravatar_for(comment.user, options = { size: 40 }) %></h1>
              <div class="comment-text">
                <h5><%= comment.user.first_name %> <%= comment.user.last_name %></h5>
                <div class="com-text"><%= comment.comment_text %></div>
                <% if comment_author(comment) %>
                  <div class="delete-btn"><%= link_to 'Delete comment', post_comment_path(post.id, comment.id), method: :delete %></div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="timeline-center">
  <div class="timeline-row">
    <div class="post-item post-page">
      <h1 class="post-img"><%= gravatar_for(@post.user, options = { size: 50 }) %></h1>
      <h5><%= @post.user.first_name %> <%= @post.user.last_name %></h5>
      <div><%= @post.content %></div>
      <%if liked?(@post) %>
        <%= link_to post_like_path(@post, liked?(@post)), method: :delete do%> 
        <i class="fa fa-thumbs-down disliked"></i> 
        <%end%>
      <% else %>
        <%= link_to post_likes_path(@post), method: :post do%>
        <i class="fa fa-thumbs-up liked"></i> 
        <%end%>
      <%end%>

      <p><%= pluralize(@post.likes.count, 'like') %></p>
      <p><%= pluralize(@post.comments.count, 'comment') %></p>
    </div>

    <section class="post-form post-show">
      <%= render  'comments/new', post: {post: @post} %>
    </section>

    <% @comments.each do |comment| %>
      <div class="post-comments">
        <h1 class="post-img"><%= gravatar_for(comment.user, options = { size: 40 }) %></h1>
        <div class="comment-text">
          <h5><%= comment.user.first_name %> <%= comment.user.last_name %></h5>
          <div class="com-text"><%= comment.comment_text %></div>
          <% if comment_author(comment) %>
            <div class="delete-btn"><%= link_to 'Delete comment', post_comment_path(@post.id, comment.id), method: :delete %></div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <aside>
      <section class="user_info">
        <div>
          <h1><%= gravatar_for user %></h1>
          <h3><%= user.first_name %> <%= user.last_name %></h3>
        </div>  
        <% unless user == current_user %>
          <% if pending?(user) %>
            <p class="friend">Friend request sent</p>
          <% elsif recieved?(user) %>
            <%= link_to 'Accept request', friendship_path(user), method: :put, class: 'btn btn-primary' %> 
          <% elsif current_user.friend_with?(user) %>
            <p class="friend">Friends</p> 
          <% else %> 
             <%= link_to 'Add Friend', "#{root_path}friends/create/#{user.id}", method: :post, class: 'btn btn-primary add_friend' %>
          <% end %>   
        <% end %>
      </section>
    </aside>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="row">
  <aside class="profile-info">
    <section class="user_info profile">
      <div>
        <h1><%= gravatar_for @user %></h1>
        <h3><%= @user.first_name %> <%= @user.last_name %></h3>
      </div>
       <%= link_to 'Edit Profile', edit_user_registration_path, class: 'btn btn-primary add_friend' %>
    </section>
  </aside>
  <div class="timeline-center">
    <div class="timeline-row">
      <ul class="post-list">
        <% @posts.each do |post| %>
          <li class="post-item post-index">
            <h1 class="post-img"><%= gravatar_for(post.user, options = { size: 50 }) %></h1>
            <h5><%= post.user.first_name %> <%= post.user.last_name %></h5>
            <div><%= post.content %></div>
            <%if liked?(post) %>
              <%= link_to post_like_path(post, liked?(post)), method: :delete do%> 
              <i class="fa fa-thumbs-down disliked"></i> 
              <%end%>
            <% else %>
              <%= link_to post_likes_path(post), method: :post do%>
              <i class="fa fa-thumbs-up liked"></i> 
              <%end%>
            <%end%>

            <p><%= pluralize(post.likes.count, 'like') %></p>
            <p><%= pluralize(post.comments.count, 'comment') %></p>
            <p><%= link_to 'Post page', post_path(post.id) %></p>
          </li>
          <div class="comment-form">
            <%= render  'comments/new', post: {post: post} %>
          </div>
          <% post.comments.each do |comment| %>
            <div class="post-comments index-comment">
              <h1 class="post-img"><%= gravatar_for(comment.user, options = { size: 40 }) %></h1>
              <div class="comment-text">
                <h5><%= comment.user.first_name %> <%= comment.user.last_name %></h5>
                <div class="com-text"><%= comment.comment_text %></div>
                <% if comment_author(comment) %>
                  <div class="delete-btn"><%= link_to 'Delete comment', post_comment_path(post.id, comment.id), method: :delete %></div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>