config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root 'posts#index'
  end
  root "static_pages#home"

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  get "/user", to: "users#show"
  get '/users', to: 'users#index'
  post '/friends/create/:id', to: 'friendships#create'
  resources :friendships, only: %i[update destroy index]
  resources :posts do
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_text, presence: true, length: { maximum: 150 }
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :sender, class_name: :User
  belongs_to :reciever, class_name: :User

  validates :sender_id, presence: true
  validates :reciever_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: %i[facebook]

  validates :first_name, presence: true
  validates :last_name, presence: true
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friendships, foreign_key: :sender_id
  has_many :inverse_friendships, class_name: :Friendship, foreign_key: :reciever_id

  def reject_request(sender)
    friendship = inverse_friendships.find { |f| f.sender == sender }
    friendship.destroy
  end

  def friend_with?(user)
    if inverse_friendships.find_by(sender_id: user.id,
                                   status: true) ||
       friendships.find_by(reciever_id: user.id, status: true)
      true
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split(' ')[0]
      user.last_name = auth.info.name.split(' ')[1]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['email'] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include FriendshipsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_comment, only: [:destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.create(comment_params)

    if @comment.save
      flash[:success] = 'Comment added'

    else
      flash[:danger] = 'Successfully failed!'
    end
    redirect_to request.referrer
  end

  def destroy
    @comment.destroy
    redirect_to request.referrer
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:comment_text, :post_id)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def new
    @friendship = Friendship.new
  end

  def create
    user = User.find(params[:id])
    friendship = current_user.friendships.create(reciever_id: user.id, status: false)
    if friendship.save
      flash[:success] = 'Friend request sent'
    else
      flash[:danger] = 'Failed'
    end
    redirect_to request.referrer
  end

  def destroy
    sender = params[:sender.id]
    reject_request(sender)
  end

  def index
    @friendships = current_user.friendships
    @inverse_friendships = current_user.inverse_friendships
  end

  def update
    sender = User.find(params[:id])
    friendship = current_user.inverse_friendships.find_by(sender_id: sender.id)
    friendship.update(status: 'true')
    friendship.save
    redirect_to request.referrer
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_find
  before_action :like_find, only: [:destroy]

  def create
    @post.likes.create(user_id: current_user.id)
    redirect_to request.referrer
  end

  def destroy
    @like.destroy
    redirect_to request.referrer
  end

  private

  def post_find
    @post = Post.find(params[:post_id])
  end

  def like_find
    @like = @post.likes.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[show index create edit update]

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = 'Post created successfully!'
      redirect_to root_path
    else
      flash.now[:danger] = "Content can't be empty!"
      @posts = Post.all
      render 'index'
    end
  end

  def edit; end

  def update; end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments.all
  end

  def index
    @post = current_user.posts.build if current_user
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show index]

  def show
    @user = current_user
    @posts = current_user.posts.all
  end

  def index
    @users = User.all
    @friendships = current_user.friendships
    @inverse_friendships = current_user.inverse_friendships
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def friend_list
    @friend_list = current_user.friendships.map { |friendship| friendship.reciever if friendship.status }
    @friend_list += current_user.inverse_friendships.map { |friendship| friendship.sender if friendship.status }
    @friend_list << current_user
    @friend_list.compact
  end

  def friend?(user)
    friend_list.include?(user)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def liked?(post)
    post.likes.find { |like| like.user_id == current_user.id }
  end

  def comment_author(comment)
    comment.user == current_user
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end

  def pending?(user)
    current_user.friendships.find_by(reciever_id: user.id, status: false)
  end

  def recieved?(user)
    current_user.inverse_friendships.find_by(sender_id: user.id, status: false)
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <nav class="facebook">
      <%= link_to "fakebook", root_path, class: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Notifications', friendships_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", user_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>  
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body-background">
    <%= render 'layouts/header' %>
    <div class="spacing"></div>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <div class="field-post">
    <%= f.label :content %>
    <%= f.text_area :content, placeholder: 'Compose new post...', class: 'field' %>
  </div>
  <%= f.submit 'Post', class: 'form-btn btn btn-primary', class: 'form-btn' %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.first_name %> <%= current_user.last_name%></h1>
<span><%= link_to 'view my profile', current_user %></span>
<span><%= pluralize(current_user.posts.count, 'post') %></span>